name: Build & Release

on:
  push:

jobs:
  build-n-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
        with:
          python-version: 3.7

      # Did some research and it looks like running the included test suite `python setup.py test`
      # will need a dynamo-local container hosted as a service in this workflow.
      - name: Testing Stub
        run: |
          echo "Stub for future automated testing"

      - name: Get version
        id: get-version
        run: |
          version=$(grep version setup.py | grep -o "[0-9].[0-9].[0-9]")
          echo "version: $version"
          echo "::set-output name=version::$version"
          #echo "::set-output name=tag_version::v$version"

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build binary wheel and source tarball
        run: python -m build --sdist --wheel --outdir dist

      - name: "Upload Build Asset: tar"
        uses: actions/upload-artifact@ee69f02b3dfdecd58bb31b4d133da38ba6fe3700
        with:
          name: graphene-pynamodb-${{ steps.get-version.outputs.version }}.tar.gz
          path: ./dist/graphene-pynamodb-${{ steps.get-version.outputs.version }}.tar.gz
          if-no-files-found: error

      - name: "Upload Build Asset: wheel"
        uses: actions/upload-artifact@ee69f02b3dfdecd58bb31b4d133da38ba6fe3700
        with:
          name: graphene_pynamodb-${{ steps.get-version.outputs.version }}-py3-none-any.whl
          path: ./dist/graphene_pynamodb-${{ steps.get-version.outputs.version }}-py3-none-any.whl
          if-no-files-found: error

      - name: Check for version bump
        id: version-bump-check
        run: |
          is_bump="false"
          old_version=$(hub release -L 1)

          if [[ "$VERSION" != "$old_version" ]]; then
            is_bump="true"
          fi

          # Testing code
          echo "old_version: $old_version"
          echo "version: $VERSION"
          echo "is_bump: $is_bump"

          echo "::set-output name=is_bump::$is_bump"
        env:
          VERSION: ${{ steps.get-version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        if: steps.version-bump-check.outputs.is_bump == 'true' && github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@95215a3cb6e6a1908b3c44e00b4fdb15548b1e09
        with:
          artifacts: |
            dist/graphene-pynamodb-${{ steps.get-version.outputs.version }}.tar.gz,
            dist/graphene_pynamodb-${{ steps.get-version.outputs.version }}-py3-none-any.whl
          commit: ${{ github.sha }}
          tag: ${{ steps.get-version.outputs.version }}
          name: "Version ${{ steps.get-version.outputs.version }}"
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
